stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
    - data/processed
    - src/features/build_features.py
    outs:
    - data/features

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/features
    - src/models/model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - model.pkl
    - src/models/model_evaluation.py
    metrics:
    - reports/metrics.json
